// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS1wWLpbD2nswhuZDM1FsGS9hO83Fd9x0',
    appId: '1:632908817300:web:e7bbda98e64fe7b146a581',
    messagingSenderId: '632908817300',
    projectId: 'boltsapp-d2b89',
    authDomain: 'boltsapp-d2b89.firebaseapp.com',
    storageBucket: 'boltsapp-d2b89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1AtzcqT3lQ9kNzKY85WPshQXbuvQNswg',
    appId: '1:632908817300:android:ecbb127daf3627e246a581',
    messagingSenderId: '632908817300',
    projectId: 'boltsapp-d2b89',
    storageBucket: 'boltsapp-d2b89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhEHqePQDSamtsAPOhI2NtOBR_FR4ZCcg',
    appId: '1:632908817300:ios:befd74815a7220fb46a581',
    messagingSenderId: '632908817300',
    projectId: 'boltsapp-d2b89',
    storageBucket: 'boltsapp-d2b89.appspot.com',
    iosBundleId: 'com.example.boltsapp',
  );
}
